### ISSUE TITLE
Could you have the current or average ping part of the time/server micro display thingy?

### ISSUE THREAD

**Issue by fuHZion** [karashiiro/PingPlugin#37] opened 2022-01-28 22:24 UTC
I currently have ping plugin rather crudely setup like this and would love if it could naturally embed.  WOLdo has this feature and it's really great!

![image](https://user-images.githubusercontent.com/98621770/151629688-584ee63e-6a92-4085-a939-329061f955d1.png)

**Comment by karashiiro** [comment] 2022-01-28 22:25
Duplicate of #30, it's planned 👍

**Closed by karashiiro** 2022-01-28 22:25 UTC
Labels: duplicate
